# print(x)

# try:
#   print(x)
# except:
#   print("An exception occurred")

# try:
#     print(x)
# except NameError:
#   print("Variable x is not defined")
# except:
#   print("Something else went wrong")

# try:
#   print("hello")
# except:
#   print("Something went wrong")
# else:
#   print("Nothing went wrong")

# x=9
# try:
#   print(x)
# except NameError:
#   print("Variable x is not defined")
# except:
#   print("Something else went wrong")
# else:
#   print("Code run success")


# try:
#   print(x)
# except:
#   print("Something went wrong")
# finally:
#   print("The 'try except' is finished")
